### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by JustinBallin** [arkangel-dev/BesiegeCreationImporter#17]
my bug report is i can't enable the addon cause the error says

![image](https://user-images.githubusercontent.com/46361235/115877290-442cfe80-a415-11eb-950e-c9dc3bcafc55.png)

**Comment by arkangel-dev** [comment]
What does the error say exactly? Im only seeing a screenshot here

**Comment by JustinBallin** [comment]
That is the error where it has the hazard symbol with the (!) on it,I tried
to enable it and it says that as in I can't enable the addon period

**Comment by arkangel-dev** [comment]
Okay, Im gonna need some more information. Can you open the system console on blender and send me a screenshot of that after you try to enable it? You can open the system console like so.

![image](https://user-images.githubusercontent.com/31138457/115904925-d0bfd700-a47e-11eb-95fc-cf65b2f97398.png)

**Comment by arkangel-dev** [comment]
Im gonna assume you figured it out now

**Comment by JustinBallin** [comment]
Nah lol
