### ISSUE TITLE
Can't download addon

### ISSUE THREAD

**Issue by Vic-921** [arkangel-dev/BesiegeCreationImporter#21]
"ZIP packaged incorrectly; __init__.py should be in a directory, not at top-level"
4.2 and 4.1

**Comment by arkangel-dev** [comment]
Hi. I've updated the zip files structure. Please try downloading and installing it once more

**Comment by Vic-921** [comment]
thanx, i got addon, but there is a new problem:


Adding component ID StartingBlock...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Adding component ID Log...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Adding component ID Log...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID ArmorPlateSmall...
Uknown block (id 57) detected...
Adding component ID ArmorPlateLarge...
Uknown block (id 57) detected...
Adding component ID ArmorPlateLarge...
Uknown block (id 57) detected...
Uknown block (id 57) detected...
Adding component ID ArmorPlateLarge...
Uknown block (id 57) detected...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID DoubleWoodenBlock...
Adding component ID Log...
Adding component ID Log...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateSmall...
Adding component ID Ballast...
Adding component ID Cannon...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID SpinningBlock...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateSmall...
Adding component ID Log...
Adding component ID DoubleWoodenBlock...
Adding component ID Hinge...
Adding component ID Hinge...
Adding component ID Hinge...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID Hinge...
Adding component ID Log...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SpinningBlock...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID ArmorPlateRound...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID Slider...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Uknown block (id 58) detected...
Uknown block (id 58) detected...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID MetalJaw...
Adding component ID MetalJaw...
Adding component ID MetalJaw...
Adding component ID MetalJaw...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Adding component ID Log...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Uknown block (id 57) detected...
Adding component ID MetalJaw...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID MetalJaw...
Adding component ID MetalJaw...
Adding component ID MetalJaw...
Adding component ID MetalJaw...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Adding component ID Log...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Adding component ID ArmorPlateLarge...
Adding component ID Log...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID MetalJaw...
Adding component ID Wheel...
Adding component ID Wheel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID Rocket...
Adding component ID MetalJaw...
Adding component ID ArmorPlateLarge...
Adding component ID WoodenPole...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID ArmorPlateLarge...
Adding component ID MetalJaw...
Adding component ID ArmorPlateLarge...
Adding component ID MetalJaw...
Adding component ID SteeringHinge...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID Swivel...
Adding component ID MetalJaw...
Adding component ID ArmorPlateLarge...
Adding component ID WoodenPole...
Adding component ID WoodenPole...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID ArmorPlateLarge...
Adding component ID MetalJaw...
Adding component ID ArmorPlateLarge...
Adding component ID MetalJaw...
Adding component ID SteeringHinge...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID Swivel...
Adding component ID WoodenPole...
Adding component ID WoodenPanel...
Adding component ID ArmorPlateLarge...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID Swivel...
Adding component ID Anglometer...
Adding component ID AnglometerNeedle...
Adding component ID Anglometer...
Adding component ID AnglometerNeedle...
Adding component ID Swivel...
Adding component ID Anglometer...
Adding component ID AnglometerNeedle...
Adding component ID Anglometer...
Adding component ID AnglometerNeedle...
Uknown block (id 76) detected...
Adding component ID WoodenPanel...
Adding component ID WoodenPanel...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Adding component ID WoodenPole...
Adding component ID WoodenPole...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID Log...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Adding component ID SteeringHinge...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID LogicGate...
Adding component ID LogicGateSwitch...
Adding component ID Timer...
Adding component ID TimerNeedle...
Adding component ID Timer...
Adding component ID TimerNeedle...
Uknown block (id 76) detected...
Adding component ID Anglometer...
Adding component ID AnglometerNeedle...
Adding component ID WoodenPole...
Adding component ID Anglometer...
Adding component ID AnglometerNeedle...
Adding component ID SteeringBlock...
Adding component ID SteeringHinge...
Uknown block (id 58) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID Log...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Adding component ID SpinningBlock...
Adding component ID Log...
Adding component ID ArmorPlateSmall...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Adding component ID Decoupler...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Special block (string) (id 7) detected...
Adding component ID BraceSectionA...
Adding component ID Timer...
Adding component ID TimerNeedle...
Uknown block (id 58) detected...
Uknown block (id 58) detected...
Adding component ID Grabber...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Uknown block (id 76) detected...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateLarge...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateSmall...
Adding component ID ArmorPlateSmall...
283 blocks imported...
234 components imported...
0 blocks skipped
Read complete in 0.08507752418518066
Importing 283 blocks...
Processing block StartingBlock
{}
Object not found : StartingBlock
Searching in C:\Users\Miha\Desktop\wat\3dprint\?\StartingBlock for skin file (type : model)...
Searching in C:\Users\Miha\Desktop\wat\3D Print\StartingBlock for skin file (type : model)...
Searching in C:\Users\Miha\Desktop\wat\StartingBlock for skin file (type : model)...
Searching in C:\Users\Miha\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BesiegeCreationImportAddon\CustomBlocks\StartingBlock for skin file (type : model)...
ERROR: Cannot find file...
Cannot read from OBJ file:''.
OBJ import of '' took 0.16 ms
Error: OBJ Import: Cannot open file ''
Traceback (most recent call last):
  File "C:\Users\Miha\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BesiegeCreationImportAddon\__init__.py", line 175, in execute
    return_data = GlobalData.importer.ImportCreation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miha\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BesiegeCreationImportAddon\blenapi.py", line 144, in ImportCreation
    imported_list.extend(self.ProcessDefaultTypeBlock(block))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miha\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BesiegeCreationImportAddon\blenapi.py", line 178, in ProcessDefaultTypeBlock
    imobject = self.BlockDrawTypeDefault(block, component, self.setting_use_vanilla_skin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miha\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BesiegeCreationImportAddon\blenapi.py", line 710, in BlockDrawTypeDefault
    current_obj = self.LookupObject(block, component, vanilla_skins)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miha\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BesiegeCreationImportAddon\blenapi.py", line 226, in LookupObject
    bpy.ops.wm.obj_import(filepath=model)
  File "C:\SteamLibrary\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: OBJ Import: Cannot open file ''

Error: Error encountered in the import process. Check console

**Comment by Vic-921** [comment]
fuck yeah, im filnally did it.
i love u guys
![aaaaaaaa](https://github.com/user-attachments/assets/1a92b45a-98b7-4af1-95a6-d448766ddc51)
